app:
  resource: "@AppBundle/Controller/"
  type: annotation

todo_list:
  resource: "@ToDoListBundle/Resources/config/routing.yml"
  prefix: /

google_task_api:
  resource: "@GoogleApiTaskBundle/Resources/config/routing.yml"
  prefix: /

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"