app:
    resource: "@AppBundle/Controller/"
    type:     annotation

ToDoListBundle:
    resource: "@ToDoListBundle/Resources/config/routing.yml"
    prefix:   /todolist


google_task_api:
    resource: "@GoogleApiTaskBundle/Resources/config/routing.yml"
    prefix:   /
