app:
    resource: "@AppBundle/Controller/"
    type:     annotation

ToDoListBundle:
    resource: "@ToDoListBundle/Resources/config/routing.yml"
    prefix:   /todolist

google_api_task:
    resource: "@GoogleApiTaskBundle/Resources/config/routing.yml"
    prefix:   /googletask
