security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern : ^/
            form_login:
                 provider: fos_userbundle
                 csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            simple_preauth:
                authenticator : google_task_api.security.authenticator
            access_denied_handler: google_task_api.security.access_denied
    
    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/callback, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/google, roles: ROLE_OK }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }