security:

    providers:
        in_memory:
            memory: ~

    role_hierarchy:
         ROLE_HAS_TOKEN: IS_AUTHENTICATED_ANONYMOUSLY

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
