security:

    providers:
        in_memory:
            memory: ~

    role_hierarchy:
         ROLE_HAS_TOKEN: IS_AUTHENTICATED_ANONYMOUSLY

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

        default:
            pattern:  ^/
            simple_preauth:
                authenticator: sf_google_api_bundle.authentificator
            access_denied_handler: sf_google_api_bundle.access_denied_handler

    access_control:
        - { path: ^/oauth/callback$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_HAS_TOKEN }