mysql:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: Password
        MYSQL_DATABASE: ToDoListDB
    ports:
        - "8081:3306"
phpmyadmin:
    image: corbinu/docker-phpmyadmin
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: Password
    links:
        - mysql
    ports:
        - "8082:80"