services:
  google_task_api.security.authenticator:
    class: GoogleApiTaskBundle\Security\Authentication\SecurityAuthenticator
         
  google_task_api.security.access_denied:
    class: GoogleApiTaskBundle\Security\Authorization\AccessDenied
    arguments: ['@happyr.google.api.client']

  google_task_api.google.home:
    class: GoogleApiTaskBundle\Google\TaskService
    arguments: ['@happyr.google.api.client', '@security.token_storage']