todo_list_homepage:
  path: /todolist/tasklist
  defaults: { _controller: ToDoListBundle:ToDoList:index}
  methods: [ GET ]

todo_list_tasks_list:
  path:	/todolist/tasklist/tasks/{listId}
  defaults: { _controller: ToDoListBundle:ToDoList:detailTasks }
  methods: [ GET, POST ]

todo_list_add_tasks_list:
  path:	/todolist/tasklist/add
  defaults: { _controller: ToDoListBundle:ToDoList:addTaskList }
  methods: [ GET, POST ]

todo_list_delete_tasks_list:
  path:	/todolist/tasklist/delete/{listId}
  defaults: { _controller: ToDoListBundle:ToDoList:deleteTaskList }
  methods: [ GET ]

todo_list_update_tasks_list:
  path:	/todolist/tasklist/update/{listId}/
  defaults: { _controller: ToDoListBundle:ToDoList:updateTaskList }
  methods: [ GET,  POST ]

todo_list_delete_task:
  path:	/todolist/tasklist/tasks/delete/{taskId}
  defaults: { _controller: ToDoListBundle:Task:deleteTask }
  methods: [ GET ]

todo_list_update_task:
  path:	/todolist/tasklist/tasks/update/{taskId}/
  defaults: { _controller: ToDoListBundle:Task:updateTask }
  methods: [ GET, POST ]
